import pickle
from sklearn.tree import DecisionTreeClassifier, export_text

def extract_tree_from_qtable(q_table_dict, feature_names, max_depth=4):
    X = []
    y = []
    
    # Iterate through the learned Q-table
    for state_tuple, actions_dict in q_table_dict.items():
        if not actions_dict:
            continue
        # Find the action with the maximum Q-value for this state
        best_action = max(actions_dict, key=actions_dict.get)
        X.append(state_tuple)
        y.append(best_action)
        
    # Fit a decision tree
    # (Constraining max_depth prevents the tree from overfitting to noise and keeps it human-readable)
    clf = DecisionTreeClassifier(max_depth=max_depth, random_state=42)
    clf.fit(X, y)
    
    # Export to readable text
    tree_rules = export_text(clf, feature_names=feature_names)
    return tree_rules

# 1. Load your fully trained Q-table model (generated by run_tournament.py)
with open('models/QT_0.pt', 'rb') as f:
    data = pickle.load(f)

# 2. Extract Bidding Rules
bid_features = ["round_num", "wizards", "high_cards", "trump_cards"]
print("--- BIDDING HEURISTIC ---")
print(extract_tree_from_qtable(data['bid_q'], bid_features, max_depth=3))

# 3. Extract Playing Rules
play_features = ["is_late_game", "tricks_needed", "position", 
                 "have_wiz_valid", "have_jest_valid", "have_trump_valid", 
                 "has_high_in_hand", "has_trump_in_hand"]
print("\n--- PLAYING HEURISTIC ---")
print(extract_tree_from_qtable(data['play_q'], play_features, max_depth=4))